import { Engine } from './shared/models/engine.enum';
import { Lawnmower } from './shared/models/lawnmower.model';

export const LAWNMOWNERS: Lawnmower[] = [
  {
    engine: Engine.COMBUSTION,
    brand: 'Bosh',
    model: 'Home and Garden ARM',
    engineDisplacement: 100,
    tankCapacity: 750,
    cuttingLevelsAmount: 5,
  },
  {
    engine: Engine.COMBUSTION,
    brand: 'Lawnmower Masterz',
    model: 'Grass Destroyer',
    engineDisplacement: 200,
    tankCapacity: 750,
    cuttingLevelsAmount: 5,
  },
  {
    engine: Engine.COMBUSTION,
    brand: 'Bosh',
    model: 'Home and Garden MRA500',
    engineDisplacement: 125,
    tankCapacity: 1000,
    cuttingLevelsAmount: 5,
  },
  {
    engine: Engine.ELECTRIC,
    brand: 'Hybix',
    model: 'Cutting Edge',
    cableLength: 20,
    bladesAmount: 4,
    color: 'Green',
  },
  {
    engine: Engine.ELECTRIC,
    brand: 'Lawnmower Masterz',
    model: 'Grass Eater',
    cableLength: 25,
    bladesAmount: 1,
    color: 'Brown',
  },
  {
    engine: Engine.ELECTRIC,
    brand: 'Bosh',
    model: 'ARS X',
    cableLength: 25,
    bladesAmount: 2,
    color: 'Yellow',
  },
  {
    engine: Engine.ACCUMULATOR,
    brand: 'Hybix',
    model: 'Edge Lord',
    accumulatorAmount: 2,
    accumulatorCapacity: 4,
    color: 'Black',
  },
  {
    engine: Engine.ACCUMULATOR,
    brand: 'Bosh',
    model: 'Faz Bar',
    accumulatorAmount: 2,
    accumulatorCapacity: 2.5,
    color: 'Orange',
  },
  {
    engine: Engine.ACCUMULATOR,
    brand: 'Random Company',
    model: 'Yes',
    accumulatorAmount: 3,
    accumulatorCapacity: 1.5,
    color: 'White',
  },
];
