import { Engine } from './shared/models/engine.enum';
import { Lawnmower } from './shared/models/lawnmower.model';

export const LAWNMOWNERS: Lawnmower[] = [
  {
    engine: Engine.COMBUSTION,
    brand: 'Bosh',
    model: 'Home and Garden ARM',
    engineDisplacement: 100,
    tankCapacity: 0.75,
    cuttingLevelsAmount: 5,
    price: 899.99,
  },
  {
    engine: Engine.COMBUSTION,
    brand: 'Bosh',
    model: 'Garden and Home ARM',
    engineDisplacement: 120,
    tankCapacity: 0.95,
    cuttingLevelsAmount: 5,
    price: 999.99,
  },
  {
    engine: Engine.COMBUSTION,
    brand: 'Lawnmower Masterz',
    model: 'Grass Destroyer',
    engineDisplacement: 200,
    tankCapacity: 0.75,
    cuttingLevelsAmount: 5,
    price: 725,
  },
  {
    engine: Engine.COMBUSTION,
    brand: 'Lawnmower Masterz',
    model: 'Cut them grass',
    engineDisplacement: 150,
    tankCapacity: 0.9,
    cuttingLevelsAmount: 3,
    price: 800,
  },
  {
    engine: Engine.COMBUSTION,
    brand: 'Bosh',
    model: 'Home and Garden MRA500',
    engineDisplacement: 125,
    tankCapacity: 1,
    cuttingLevelsAmount: 5,
    price: 620,
  },
  {
    engine: Engine.ELECTRIC,
    brand: 'Hybix',
    model: 'Cutting Edge',
    cableLength: 20,
    bladesAmount: 4,
    color: 'Zielony',
    price: 450,
  },
  {
    engine: Engine.ELECTRIC,
    brand: 'Hybix',
    model: 'Lorem',
    cableLength: 15,
    bladesAmount: 3,
    color: 'Zielony',
    price: 350,
  },
  {
    engine: Engine.ELECTRIC,
    brand: 'Hybix',
    model: 'Ipsum',
    cableLength: 15,
    bladesAmount: 3,
    color: 'Żółty',
    price: 300,
  },
  {
    engine: Engine.ELECTRIC,
    brand: 'Lawnmower Masterz',
    model: 'Grass Eater',
    cableLength: 25,
    bladesAmount: 1,
    color: 'Brązowy',
    price: 420,
  },
  {
    engine: Engine.ELECTRIC,
    brand: 'Lawnmower Masterz',
    model: 'Neighbour alarm',
    cableLength: 35,
    bladesAmount: 3,
    color: 'Czarny',
    price: 550,
  },
  {
    engine: Engine.ELECTRIC,
    brand: 'Bosh',
    model: 'ARS X',
    cableLength: 25,
    bladesAmount: 2,
    color: 'Żółty',
    price: 840,
  },
  {
    engine: Engine.ELECTRIC,
    brand: 'Bosh',
    model: 'BOI V',
    cableLength: 15,
    bladesAmount: 2,
    color: 'Różowy',
    price: 500,
  },
  {
    engine: Engine.ACCUMULATOR,
    brand: 'Hybix',
    model: 'Edge Lord',
    accumulatorAmount: 2,
    accumulatorCapacity: 4,
    color: 'Czarny',
    price: 899.99,
  },
  {
    engine: Engine.ACCUMULATOR,
    brand: 'Hybix',
    model: 'Good sleep killer',
    accumulatorAmount: 3,
    accumulatorCapacity: 1,
    color: 'Fioletowy',
    price: 699.99,
  },
  {
    engine: Engine.ACCUMULATOR,
    brand: 'Bosh',
    model: 'Faz Bar',
    accumulatorAmount: 2,
    accumulatorCapacity: 2.5,
    color: 'Pomarańczowy',
    price: 459.99,
  },
  {
    engine: Engine.ACCUMULATOR,
    brand: 'Bosh',
    model: 'Hello There',
    accumulatorAmount: 3,
    accumulatorCapacity: 4.5,
    color: 'Ekri',
    price: 559.99,
  },
  {
    engine: Engine.ACCUMULATOR,
    brand: 'Random Company',
    model: 'Yes',
    accumulatorAmount: 3,
    accumulatorCapacity: 1.5,
    color: 'Biały',
    price: 500,
  },
  {
    engine: Engine.ACCUMULATOR,
    brand: 'Random Company',
    model: 'No',
    accumulatorAmount: 2,
    accumulatorCapacity: 3,
    color: 'Biały',
    price: 300,
  },
  {
    engine: Engine.ACCUMULATOR,
    brand: 'Random Company',
    model: 'Maybe',
    accumulatorAmount: 4,
    accumulatorCapacity: 5.5,
    color: 'Biały',
    price: 299.99,
  },
];
